# Site settings
title: Ray's Remedy
description: make physicians' lives easier...
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "JeRui Chang"
  email: "jrchang612@gmail.com"
  url: "https://jrchang612.github.io/blog"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
comments: true
